### ISSUE TITLE
Women catching up – NY Marathon [Project]

### ISSUE THREAD

**Issue by MarinaBraem** [jsoma/data-studio-projects#18]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at ...

# Pitch
Women catching up – NY Marathon 

## Summary
I want to examine the starters from the begin (1970) until today and to compare the relation between male and female runners and to show the smaller and bigger gaps. 

**IDEA LINK** 
Inspiration from the New York Times – a very nice animation about the running time: 
https://www.nytimes.com/interactive/2015/10/30/sports/new-york-marathon-in-six-charts.html?_r=0
<img width="791" alt="newyorktimes_waves_runningtime_03" src="https://user-images.githubusercontent.com/28846818/28478992-9becb786-6e28-11e7-99d8-eb01fd5d7f24.png">

**RESEARCH**
I prepared a camparison MEN/WOMEN with screenshots from the data site "Marathonstatistics", relateted by age and running time from 1999 and 2016:
https://marathonstatistik.com/zeiten-newyork.html 
<img width="603" alt="marathonstatistik_01" src="https://user-images.githubusercontent.com/28846818/28479548-d85f88f4-6e2a-11e7-9c92-edad113717af.png">

## Details
https://www.nytimes.com/interactive/2015/10/30/sports/new-york-marathon-in-six-charts.html
https://marathonstatistik.com/newyork.html
http://results.nyrr.org/home
http://www.tcsnycmarathon.org/about-the-race/results/finisher-demographics

**Possible headline(s):** 
Women catching up

**Data set(s):** 
https://marathonstatistik.com/newyork.html

**Code repository:** 
https://github.com/MarinaBraem/New-Data-Studio/blob/master/Code/Project1_NY_Marathon_Starters/List_Marathons.xlsx

http:///Users/marinabram/Desktop/LEDE_2017_Part2/04_DataStudio/New-Data-Studio/docs/01_Marathon_Women/01_Marathon_Women.html
	
**Possible problems/fears/questions:** 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [ ] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [ ] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by ElisaHarlan** [comment]
Beautiful idea! The most interesting questions to me are: How much time did women and men in comparison need to finish a marathon? How did women catch up? How many women and men took part in the marathon (past and present)? You could also do great visualizations with it!!!

**Comment by zuxinyi** [comment]
Also I believe the number of women runners is also increasing and the portion of women runners change overtime. It is also interesting to show that women are getting more involved in marathon!

**Comment by kcough** [comment]
This is a really interesting idea! This is something that's a little different but along the lines of what you want to look at, for inspiration:
http://www.tcsnycmarathon.org/analytics

Here are some interesting datasets, because I think the most difficult thing at this point is finding something you can work with without going through lots of complicated scraping. Also I would draw out what you are envisioning as the end product--that might help direct your research!

http://www.marathonguide.com/results/browse.cfm?MIDD=472161106

You have to pass parameters to get results--some of it seems to be broken. But here's the top 100 finishers for 2016 in a more readily available format that you could copy/paste into a text editor.
http://www.marathonguide.com/results/browse.cfm?RL=1&MIDD=472151101&Gen=B&Begin=1&End=100&Max=49828

This is a cool visualization of where people cheat during the NYC marathon:
 http://www.nytimes.com/imagepages/2009/10/31/sports/olympics/01runnergfx.html?action=click&contentCollection=Sports&module=RelatedCoverage&region=EndOfArticle&pgtype=article

And the story behind it: http://www.nytimes.com/2009/11/01/sports/01runners.html?_r=1&scp=3&sq=marathon&st=cse

**Comment by MarinaBraem** [comment]
# Update
	
## Content

**VISUALIZATION IN  ILLUSTRATOR**
file:///Users/marinabram/Desktop/LEDE_2017_Part2/04_DataStudio/New-Data-Studio/docs/01_Marathon_Women/01_Marathon_Women.html
I worked on a short visual concept in illustrator with my basic graph from pandas to see if it's possible to cover my headline and my data in a clear guided way. I developed a simple grid (matrix) to compare the aspects of my gap between men/women.

<img width="1038" alt="entwurf_04" src="https://user-images.githubusercontent.com/28846818/28500263-fd9b3e2e-6f92-11e7-97f8-a0028f78e8bc.png">
	
## Any changes in direction or topic?
No. After my research I could visualize my thesis. The gap becomes smaller – women are catching up! The numbers grew at the starting places by women – but not as expected the running time of the winner women. The really small gap is constantly the same between men and women: ONLY 15 MINUTES – since almost 50 years.

<img width="428" alt="screenshot 2017-07-22 01 41 20" src="https://user-images.githubusercontent.com/28846818/28488753-e17c1b6a-6e7e-11e7-8614-a068e8fa7003.png">

**NEXT STEPS**
Next I would like to do a deeper research (if it's possible) in time data by the hobby sportsmen-/ women. Because the marathons became a really popular sport and I think it would be important to look more closely now to these aspects. Another small detail I like very much is the country aspect by the winners. As an example: There are 10 Norwegian winners among the women, but no Norway winner from the men. 

<img width="567" alt="screenshot 2017-07-22 01 42 42" src="https://user-images.githubusercontent.com/28846818/28488762-1d5d3e70-6e7f-11e7-924f-97c94276aeb0.png">

<img width="702" alt="screenshot 2017-07-22 01 48 38" src="https://user-images.githubusercontent.com/28846818/28488784-f4674cda-6e7f-11e7-8fbe-76553ed29abc.png">

## Problems/Questions
How do I get the total running times and how do I deal with this data?

## Checklist
	
- [x] I have included my visuals
- [x] have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by MarinaBraem** [comment]
# Final

## Project visuals/text
> The visualization shows the increase in female participants in the most popular marathon in the world – The New York City Marathon. The increase is linked to the historical issue of women in  marathons and collected to the actual status of female participants in the today 6 most 
important marathons of the world (WMM: World Major Marathons). It shows where women status is today and that there are still big differences between the US, Europe and Asia.
Women Catching Up – Yes! But in different ways.

![women_catching_up_finish](https://user-images.githubusercontent.com/28846818/28804873-2a7947f4-7634-11e7-851f-ce98dd49db89.png)


## Details
The difficulty was to research the data within the short time and to point out in the same time a clear statement. How is the relevance conveyed? What data creates a context that makes the framework usefull? How should the data be linked and which comparisons and facts show both:  the initial situation and the development? In the end, I worked with small additions to give the story a clearer direction. I worked with absolute numbers, percentages and a really rough timeline.

**Headline:** 
Women Catching Up

**Published website version:**
https://marinabraem.github.io/New-Data-Studio/

**Code repository:**
https://github.com/MarinaBraem/New-Data-Studio/tree/master/Code/Project1_Marathon_Women

**Final data set(s):** 

## What did you find to be the most difficult part of this project?
The current state shows a rough direction. The data depth is still superficial. The statement and idea seems to make sense. The question arises in which direction supplementary data will have even more relevance and impact.

## Are you satisfied with what you produced? Is there anything you would like to change or improve? 
It is a very important experience for me to work on a project like this and to explore both sides: the potential and the difficulties of the topic.

## Checklist
- [x] I have included my visuals
- [x] I have posted my project to my project website
- [ ] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository

**Comment by qdinhbui2** [comment]
You need to annotate your charts more. There is no y axis. The piece might be better if you expressed the data women as a percentage of all runners. That way you can control for secular changes running interest. 

Then you need to do some reporting to get an idea of why these trends are happening. Right now you have a good picture. Now build it out into a narrative.

**Comment by MarinaBraem** [comment]
Hi Bui! Thank you for the comment. This is not the whole graphic and story. I upload the result in the next hour – just have to fix some issues.

**Comment by MarinaBraem** [comment]
# Update
> Thinking about a new storytelling format as an article and with the feedbacks from Bui. 
Work in progress. 
<img width="451" alt="screenshot 2017-08-01 18 08 01" src="https://user-images.githubusercontent.com/28846818/28849286-650c56a8-76e4-11e7-8daf-db2d5d8287e0.png">


## Content
 Running Nations
> Text is comming 
	
## Any changes in direction or topic?
	
## Problems/Questions
	
## Checklist
	
- [ ] I have included my visuals
- [ ] I have added writing about my topic
- [ ] I have been updating my DIARY.md with details about my process
- [ ] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [ ] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
Hi Marina,
So I spent a long time staring at the chart 'Steps of increasing' to figure out what the black meant-- is it a chart? No, I think it is just mean to be a shadow! Ah, this is not necessary. Worry less about decorating your charts to begin with. Though, to be clear, you have designed something very nice here. That chart, the 'since' label. I would just move them to be close to the data. And then just say New York, 1971 right next to that data point. It's less work for the readers.

So I disagree that this should be a percentage. This is all about runners, and all about people so we want to know how many women, how many men.  I agree, that we need to have a scale on these data. We want the axis to guide of through how many there are at each time period.

Here is another way to do multiple pies, you can make stacked bar charts and they are easier to compare and easier to label.

![screen shot 2017-08-07 at 9 28 05 pm](https://user-images.githubusercontent.com/659014/29052344-71a6c59c-7bb7-11e7-8432-84af9ac26552.png)

Overall tho, I like this direction.
