### ISSUE TITLE
Death in the Mountains [Project]

### ISSUE THREAD

**Issue by peterjost** [jsoma/data-studio-projects#50]
# Pitch

## Summary
Every year, dozens die in the Swiss Alps during sports activity. What kind of sport is the most dangereous up in the mountains? How old are the victims? Where do they com from? 
And why do they die?

## Details
The BFU, the Swiss Competence Centre for Accident Prevention, releases a bunch of statistics around accidents. One focus lies on mountain sports, because there are many accidents up in the mountains, the injuries are severe and the rescue operations expensive. I want to explore this data of mountain accidents to find patterns in terms of age, kind of sports and country.

**Possible headline(s):** 
Falling down - how it is, and how not
Climbing is dangereous? Sure, but ...
Swiss Alps - the grave of the brave

**Data set(s):** 
http://www.bfu.ch/de/forschung-und-statistik/statistik 

**Code repository:** 
https://github.com/peterjost/studio-projects
	
**Possible problems/fears/questions:** 
Is there a clear trend in the data?

## Work so far
- Explored the data
- made some basic visualization

![image](https://user-images.githubusercontent.com/28814371/28571100-493a591e-710f-11e7-9465-37d7f3595b95.png)

![image](https://user-images.githubusercontent.com/28814371/28570773-a9a62d34-710d-11e7-8728-d79822ab6246.png)

![image](https://user-images.githubusercontent.com/28814371/28571048-f87a4048-710e-11e7-96bf-0e346bd40ed5.png)

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by simon-pinkmartini** [comment]
A nice topic, since many people in Switzerland are into mountain sports (and many people know somebody who has had a fatal accident in the mountains). What struck me with your chart is that the highest number of deaths occurs within the 40-49 years old bracket. This is surprising. I would have thought that most accidents involve younger people, adventurers who are willing to take on large risks. But the data tells us a different story: That you have the highest risk of dying in the alps when you are a middle-aged person, perhaps because you are overestimating your physical abilities and doing hikes / climbs that you shouldn't be doing any more. Maybe you can focus on this age category.

**Comment by chrgavalas** [comment]
Interesting topic! Especially now that most of your peers start reserving their winter vacations up in the mountains! I definitely agree with Simon, it's quite striking to see that most people who lose their lives are in the 40-49 age group. Is there also maybe a trend over time? Has it gone better or worse? And has there been any regulation passed that maybe explains it?

**Comment by peterjost** [comment]
# Update
	
## Content

![image](https://user-images.githubusercontent.com/28814371/28646893-12b8bd62-7232-11e7-9851-6c4da4a32290.png)

![image](https://user-images.githubusercontent.com/28814371/28800184-95bc5346-7619-11e7-8099-11cb80417a76.png)

![image](https://user-images.githubusercontent.com/28814371/28800209-b3b3875c-7619-11e7-9a5d-b1f5bb5c30cb.png)

![image](https://user-images.githubusercontent.com/28814371/28800296-0bab6f38-761a-11e7-866f-2ce79a7ca396.png)

![image](https://user-images.githubusercontent.com/28814371/28800175-8a85bf26-7619-11e7-9076-bde6b28c4ee1.png)






## Any changes in direction or topic?
Big surprise! There are more hikers involved in Fatalities in the Swiss mountains than mountaineers or climbers. And not the young and wild ones are the agegroup with the highest number of death people, no, the agegroup of 50+. Most of them are hikers.

## Problems/Questions
Styling the graphs needs a lot of time.

## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by peterjost** [comment]
# Update
	
## Content

# Climbing is dangerous? Sure, but...

The Swiss Alps. They are a paradise for mountaineers, climbers and hikers. But every summer dozens of these braves find in the mountains their graves. More than 8000 people are involved in accidents in the Swiss mountains every year  - 82 ended with fatalities last year. 

The most common accident cause is falling. And, big surprise: Hikers are involved in 2 out of 3 fatalities. Why? Carelessness, inattentiveness and fatigue lead to stumbling, which can lead to falls - often with disastrous consequences. Frequently there is also a lack of careful planning. If there are no energy reserves, however, surprising difficulties such as weather shifts can quickly lead to delicate situations.

Mountain hiking is very popular among seniors. Unfortunately, this is also reflected in the accident figures: Half of the fatal accidents affect persons over 60 years, most of them are male hikers. Why? We can only speculate. May be they didn't match the fitness level for the chosen hiking trip. And may be they don't have in mind, that with increasing age the balance and reactivity decreases. Shortly said: They underestimate the requirements.

Genereally, hiking trips needs some preparation. And once you're on your way, hiking will be a pleasant and safe experience for everyone if you stick to a few basic rules. Hiking is not an extreme sport, but hiking in the mountains is not to be underestimated. High Alpine terrain is easily accessible in Switzerland. Anyone can get there and start hiking. This could be a dangerous situation in itself. Unprepared and inexperienced hikers are more likely to run into trouble. 

Here are some useful tips:

- Do not leave the marked route. There are signposts and marks on rocks, fences, etc. that help you to find your way;

- Trails are mostly not paved. They're rocky, full of tree roots or steep. Concentrate on the trail while walking. Stop to look around and admire the view;

- Do not pause at places with lots of loose rocks on a slope. A stone avalanche might have taken place here and it can happen again;

- Do not pause very close to brooks. They can transform into a lethal torrent of water due to heavy weather conditions elsewhere. It can occur even quicker in case the brook or river is also in use to drain away water from a hydro-electric power station. The amount of water can increase dramatically in no time;

- Keep an eye on the weather and adjust your plan if the weather turns bad. If necessary, take the shortest route back to a nearby village. Forecasts on a mobile phone are more useful;

- Have the phone numbers of rescue services at hand, and contact them in case you need immediate medical assistance. Provide clear information about your location. 

- Make sure that someone who's not hiking along knows which route you'll take that day.





![image](https://user-images.githubusercontent.com/28814371/28808044-459dab16-7647-11e7-9950-86997d7dc7b9.png)

![image](https://user-images.githubusercontent.com/28814371/28831901-0698e838-76a9-11e7-807c-2694cdb2c8fd.png)

![image](https://user-images.githubusercontent.com/28814371/28808169-f308f9cc-7647-11e7-9781-cbfd31c9672f.png)

![image](https://user-images.githubusercontent.com/28814371/28831913-1072cf0e-76a9-11e7-9422-a7e061f9bf50.png)

![image](https://user-images.githubusercontent.com/28814371/28832121-a4161888-76a9-11e7-91b7-111a32d9c907.png)


## Any changes in direction or topic?
No. Changed the graphs into some mountain-like ones.
	
## Problems/Questions
	
## Checklist
	
- [x] I have included my visuals
- [x] I have added writing about my topic
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
- [x] I have received two comments of peer feedback on my project update

**Comment by sarahslo** [comment]
Peter, so, I don't think the number of deaths is quite constant as you state. It looks like in 2011 there were over 100 deaths in in 2012 only about 60. That is a big difference. That is all your classmates and each of their significant others.

What I do see here that the number of deaths is more a reflection of the number of people who do a certain sport than is is the chances that you are going to die doing that sport. You have not normalized these data.

If I look at this it looks like climbing and canyoning are safe sports. But if you take the total number of climbers deaths each year and divide them by the total number of climbers what percentage do you get? If there are 1,000 hikers and 300 die, that is 30% of all hikers. But if there are 100 climbers and 50 die -- that's 50%. So a smaller number may die by climbing, but it's a riskier sport.

The age group chart in your first draft is charted properly. We should not use fever lines for this, because that implies there is a connection between the datapoints that there is not. What is interesting there is you see 70 yr olds are more likely to die by hiking but people in their 20s die by climbing the most of all ages. I'd want to find out how many people of each age do each sport and how likely they are to die from it, and what are those relationships.

This is an excellent dataset and a good start. You have, however, just scraped the surface. It's plotted very clearly and I like that you show us different things. But remember to look for what is really different in the dataset.

Nice work.

**Comment by peterjost** [comment]
# Final

## Project visuals/text
![image](https://user-images.githubusercontent.com/28814371/28939305-d7957b34-785e-11e7-990e-087b5cad1b88.png)

## Details

**Headline:** 
Do you like Hiking? Then you should better read this!
**Published website version:**
https://peterjost.github.io/studio-projects/deathmountains/
**Code repository:**
https://github.com/peterjost/studio-projects
**Final data set(s):** 
https://github.com/peterjost/studio-projects/blob/master/code/Death%20in%20the%20mountains/death_in_the_mountains.ipynb

## What did you find to be the most difficult part of this project?
Handling two projects at the same time - and having algorithms class, to.

## Are you satisfied with what you produced? Is there anything you would like to change or improve?
It is a good second step, I guess. It would take more time to do better research and to finally get a better result.

## Checklist

- [x] I have included my visuals
- [x] I have posted my project to my project website
- [x] I have been updating my DIARY.md with details about my process
- [x] I have uploaded/updated any Jupyter Notebooks or other datasets into my code repository
