### ISSUE TITLE
Women's Empowerment in India [Project]

### ISSUE THREAD

**Issue by amandolinjames** [jsoma/data-studio-projects#87]
Please complete all of the following sections, or a robot will spookily dance around your issue! A completed version of this template can be found at https://github.com/jsoma/data-studio-projects/issues/1

# Pitch
How have women become more empowered in India in the past ten years? How do the rural areas compare to the urban areas? 

## Summary
For each of India’s 36 states and Union Territories, the country’s latest National Family Health Survey for 2015-2016 reported on women’s empowerment and gender based violence metrics. The data includes information on the percentages of “ever-married women who have ever experienced spousal violence” and “women having a bank or savings account that they themselves use.” I want to look at how the women's empowerment varies in the urban areas vs. rural areas. 

## Details
![screen shot 2017-08-08 at 9 06 12 pm](https://user-images.githubusercontent.com/29207139/29101049-bf79e648-7c7d-11e7-8693-4960aa2a6041.png)

![screen shot 2017-08-08 at 9 08 56 pm](https://user-images.githubusercontent.com/29207139/29101118-392ee4ca-7c7e-11e7-8d43-abe2e2e73866.png)

![screen shot 2017-08-08 at 9 11 39 pm](https://user-images.githubusercontent.com/29207139/29101125-3b2e9afe-7c7e-11e7-803d-8194d251ab41.png)

**Possible headline(s):** 

**Data set(s):** 
From Data is Plural Spreadsheet
**Code repository:** 

**Possible problems/fears/questions:** 
I'd like to look at this over time, but for most of the questions there is only data for 2015-16. I'm still figuring out how I'd like to visualize it. 
## Work so far

##Update 

From getting valuable feedback, I'm going to look further into a few areas: Dadra and Nagar Haveli to explore why they have the biggest gaps. I'm still trying to figure out the best way to show these indicators on a chart- and am leaning in the direction of focusing on mobile phones in particular. I am also planning to group the areas by region since most people aren't familiar with where the different states in India are located. 

## Checklist

This checklist must be completed before you submit your draft.

- [x] I have already spent time with my data set, opening it, exploring it, etc
- [x] I have created a "DIARY.md" file to save links and list all of the terrible, no good problems I come across
- [x] My issue issue has `[Project]` in the title
- [x] My issue links to my data set(s)
- [x] My issue links to my code repository
- [x] My issue explains what I'd like to explore in the data set
- [x] My issue includes images - either inspiration or what I've done so far
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by Ediegram** [comment]
from your email: 
"I wanted to ask you: would it make sense to put them all on one graph, instead of three separate graphs? In terms of a story, what I found most surprising is that women in rural areas are more likely to have their own cell phone. I thought of just making a chart of that one, but the other graphs are interesting too. "
have you thought about looking deeper into some of these areas, such as Dadra and Nagar Haveli? Its the region with the biggest gaps ... and goes against expectations.
You can also look into traditional indicators of women's empowerment such as the number of children, maternal health, education levels or political representation, etc.
If you do put the charts together, try grouping the three charts (small) by region ..
